// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Y9tkP7Jm0mhU1x8GGoC5MP5gyrn4ObU',
    appId: '1:611249398839:web:4ec60090461655adb78bb2',
    messagingSenderId: '611249398839',
    projectId: 'fir-tutorial-f48c2',
    authDomain: 'fir-tutorial-f48c2.firebaseapp.com',
    databaseURL: 'https://fir-tutorial-f48c2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-tutorial-f48c2.firebasestorage.app',
    measurementId: 'G-W7LDR6VKGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: '1:611249398839:android:73e474c997b79515b78bb2',
    messagingSenderId: '611249398839',
    projectId: 'fir-tutorial-f48c2',
    databaseURL: 'https://fir-tutorial-f48c2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-tutorial-f48c2.firebasestorage.app',
  );
}
